[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "traverser-ai-api"
version = "0.1.0"

[project.scripts]
run-cli = "traverser_ai_api.cli_controller:main_cli"

[tool.setuptools.packages.find]
where = ["."]
include = ["traverser_ai_api*"]